### ISSUE TITLE
Use hashbow for default domain colors

### ISSUE THREAD

**Issue by fiatjaf** [joseph-jalbert/colortabs#1]
Instead of having to define a color for each domain, assign default colors for every domain with https://www.npmjs.com/package/hashbow, let people change the defaults if they want.

This only requires a change at https://github.com/joseph-jalbert/colortabs/blob/master/scripts/switcher.js#L34

**Comment by joseph-jalbert** [comment]
Hi @fiatjaf,
Thanks for your suggestion. Also, sorry for the very long delay in my response; my notifications are not working. The original purpose of this tool is for the user to be able to assign colors to domains that are important to them from a productivity standpoint. Please feel free to fork and add the default colors feature if you wish. Hashbow is a cool library, thanks for letting me know about it.
-Joe
