### ISSUE TITLE
Import/export color configurations

### ISSUE THREAD

**Issue by ComputerDaddyGuy** [joseph-jalbert/colortabs#2]
Hi,
Could you please add a feature to import/export color configurations, so I can easily share it with my colleagues ?
Thanks !

**Comment by joseph-jalbert** [comment]
Hi @ComputerDaddyGuy ,
Thanks for using ColorTabs. That's a great idea! I will implement it when I have some free time. Sorry for the delay in my response, for some reason I am not getting notifications.

**Comment by joseph-jalbert** [comment]
@ComputerDaddyGuy, import/export has been implemented in the just-now-released version 1.2, available here: https://addons.mozilla.org/en-US/firefox/addon/colortabs/ Thanks again for your feedback and the great idea. I hope you continue to enjoy using ColorTabs
