### ISSUE TITLE
Fine grained control for domain

### ISSUE THREAD

**Issue by isreport** [joseph-jalbert/colortabs#3]
Hi,
Could you consider adding an option to specify port in combination with domain?
I find the extension highly useful because it helps me easily identify which environment im using now(production v local) but even in local environment i get to test few different versions sometimes so it would be nice to have an option to distinguish them. I think domain color can be set as default and adding port specific entry for color could be one way of doing this. What do you think?
Thanks.

**Comment by joseph-jalbert** [comment]
Hi @isreport,
Thanks for your suggestion. Port specificity is a great idea. What do you mean by setting domain color as default? My initial thinking is to treat every domain/port combination as unique and specify a color for each.

**Comment by isreport** [comment]
@joseph-jalbert
Hi, sorry it took while to write back.
By domain default color I meant like say hostA is blue and therefore hostA:8088 or hostA:8080 is blue too but assigning hostA:9000 as green is an option. So color for host entry alone is like default color with an option to set host+port color combination additionally. Hope i made sense and honestly any implementation about this would be nice to have.
Thanks!

**Comment by joseph-jalbert** [comment]
Thanks @isreport, that makes sense and is a good idea. I've been too busy recently to have time to work on this, but hopefully that will be changing in the upcoming weeks. I'll keep you posted.

**Comment by joseph-jalbert** [comment]
Good news @isreport, port-specific entries are now supported in version 1.3: https://addons.mozilla.org/en-US/firefox/addon/colortabs/ Thanks again for your feedback and the idea, and please let me know if you have any questions.
-Joe
